# Generated by Django 2.0.3 on 2018-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_option_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='option',
        ),
        migrations.RemoveField(
            model_name='price',
            name='pizza_type',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(null=True, to='orders.Topping'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
