# Generated by Django 2.0.3 on 2018-04-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180407_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza_assembly',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='pizza_assembly',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas_assemblies',
            field=models.ManyToManyField(to='orders.Pizza_Assembly'),
        ),
    ]
