# Generated by Django 2.0.3 on 2018-04-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180415_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinner_plates',
            field=models.ManyToManyField(to='orders.Item'),
        ),
    ]
