# Generated by Django 2.0.3 on 2018-04-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180415_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner_plate',
            name='item',
        ),
        migrations.DeleteModel(
            name='Dinner_Plate',
        ),
    ]
